---

- name: deploy tidb-lightning binary
  copy: src="{{ resources_dir }}/bin/tidb-lightning" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes
  register: tidb_lightning

- name: deploy tidb-lightning-ctl binary
  copy: src="{{ resources_dir }}/bin/tidb-lightning-ctl" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes
  register: tidb_lightning_ctl

- name: backup tidb-lightning binary file
  command: mv "{{ tidb_lightning.backup_file }}" "{{ backup_dir }}"
  when: tidb_lightning.changed and tidb_lightning.backup_file is defined

- name: backup tidb-lightning-ctl binary file
  command: mv "{{ tidb_lightning_ctl.backup_file }}" "{{ backup_dir }}"
  when: tidb_lightning_ctl.changed and tidb_lightning_ctl.backup_file is defined

- name: create run script
  template:
    src: "{{ item }}_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - start_lightning
    - stop_lightning
    - tidb_lightning_ctl
  register: lightning_script

- name: backup script file
  command: mv "{{ item.backup_file }}" "{{ backup_dir }}"
  when:
    - item.changed
    - item.backup_file is defined
  with_items: "{{ lightning_script.results }}"
